MirrorApiBundle\Entity\User:
    attributes:
        id:
            groups: ['user', 'module']
        firstName:
            groups: ['user', 'module']
        lastName:
            groups: ['user', 'module']
        photoName:
            groups: ['user', 'module']
        modules:
            groups: ['user']


MirrorApiBundle\Entity\Module:
    attributes:
        id:
            groups: ['user', 'module']
        name:
            groups: ['user', 'module']
        position:
            groups: ['user', 'module']
        user:
            groups: ['module']

MirrorApiBundle\Entity\Time:
    attributes:
        id:
            groups: ['user', 'module']
        name:
            groups: ['user', 'module']
        position:
            groups: ['user', 'module']
        timeZone:
            groups: ['user', 'module']
        user:
            groups: ['module']


MirrorApiBundle\Entity\Weather:
    attributes:
        id:
            groups: ['user', 'module']
        name:
            groups: ['user', 'module']
        position:
            groups: ['user', 'module']
        city:
            groups: ['user', 'module']
        country:
            groups: ['user', 'module']
        user:
            groups: ['module']
