MirrorApiBundle\Entity\User:
    exclusion_policy: none
    properties:
        id:
            groups: ['user', 'module']
        firstName:
            groups: ['user', 'module']
        lastName:
            groups: ['user', 'module']
        photoName:
            groups: ['user', 'module']
        modules:
            groups: ['user']